### ISSUE TITLE
Provide readable examples for manual distribution

### ISSUE THREAD

**Issue by Downchuck** [cockroachdb/cockroach-prod#26]
The current cockroach README works for a single node, and the current cockroach-prod works provided you use the shell. At present, I don't see the steps involved with manually managing a cluster, whether using AWS ECS or EC2 directly (or EMR or some other acronym).

**Comment by tamird** [comment]
This issue refers to scripts that now reside in the main repo. Furthermore, I don't really know what's being asked for here, so I'm going to close this. Please reopen in the main repo if you feel there's work to be done there.
