### ISSUE TITLE
TLS

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach-prod#63]
Now that we're going to build more tools around this, we should move to TLS quickly. As far as I'm concerned, using a bunch of test-only certs which are simply uploaded is fine.

**Comment by mberhault** [comment]
agreed, I'll prioritize that.

**Comment by tamird** [comment]
Anything left to do here, or does this belong in the main repo?

**Comment by tamird** [comment]
Looks stale to me.
