### ISSUE TITLE
stress test reporting is broken

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach-prod#98]
see: `http://<secret CI server URL>/viewLog.html?buildId=891&buildTypeId=Cockroach_StressTests&tab=buildLog#_state=311&focus=3322`

The logs here contain several interesting things:
> `GITHUB_API_TOKEN variable not set, not posting issues.`

> `MAILTO variable not set, not sending email.`

> `766 runs completed, 1 failures, over 44s`

> `347 runs completed, 1 failures, over 13m4s`

This has been broken since the move to `<secret CI server>` on 2016-06-27. It is also worrying that the CI server is reporting these tests to have succeeded.

cc @petermattis

**Comment by tamird** [comment]
Always-green status seems related to https://github.com/cockroachdb/cockroach-prod/issues/59.

**Comment by jordanlewis** [comment]
This should be fixed by #100.

**Comment by tamird** [comment]
Let's leave this open until some emails go out.

**Comment by jordanlewis** [comment]
Closing this, #104 encapsulates getting the emails back to their previous standards.
